# Add application configuration variables here, as shown below.
#
SENDGRID_USERNAME: 
SENDGRID_PASSWORD: 

STRIPE_PUBLISHABLE_KEY:
STRIPE_SECRET_KEY:

development:
  SECRET_KEY_BASE: 
  DATABASE_USERNAME: 
  DATABASE_PASSWORD: 

test:
  SECRET_KEY_BASE: 
  DATABASE_USERNAME: 
  DATABASE_PASSWORD: 
