# Add application configuration variables here, as shown below.
#
SENDGRID_USERNAME: 
SENDGRID_PASSWORD: 

development:
  SECRET_KEY_BASE: 
  DATABASE_USERNAME: 
  DATABASE_PASSWORD: 

test:
  SECRET_KEY_BASE: 
  DATABASE_USERNAME: 
  DATABASE_PASSWORD: 
